name: balance
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
dependencies:
  - python=3.12
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - rasterio>=1.3.0
  - gdal>=3.5.0
  - exactextract
  - xarray>=2023.0.0
  - rioxarray>=0.13.0
  - geopandas>=0.12.0
  - shapely>=2.0.0
  - pyproj>=3.0.0
  - rasterstats>=0.17.0

